version: 3

tasks:
  check:
    desc: 開発環境が整っているかチェック
    cmds:
      - |
        echo "開発環境をチェックしています..."
        if ! command -v docker &> /dev/null; then
          echo "エラー: dockerがインストールされていません"
          exit 1
        fi
        echo "✓ docker: $(docker --version)"
        if ! command -v rustc &> /dev/null; then
          echo "エラー: rustがインストールされていません"
          exit 1
        fi
        RUST_VERSION=$(rustc --version | grep -oE '[0-9]+\.[0-9]+' | head -1)
        RUST_MAJOR=$(echo $RUST_VERSION | cut -d. -f1)
        RUST_MINOR=$(echo $RUST_VERSION | cut -d. -f2)
        if [ "$RUST_MAJOR" -lt 1 ] || ([ "$RUST_MAJOR" -eq 1 ] && [ "$RUST_MINOR" -lt 91 ]); then
          echo "エラー: rust 1.91以上が必要です (現在: $(rustc --version))"
          exit 1
        fi
        echo "✓ rust: $(rustc --version)"
        echo "開発環境のチェックが完了しました"

  gen:api:
    desc: openAPIからコードを生成
    cmds:
      - docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate -i /local/docs/api.yaml -g rust-axum -o /local/generated --additional-properties=packageName=generated

  gen:crunch:
    desc: crunchをビルド
    cmds:
      - |
        if [ "$(uname)" = "Darwin" ]; then
          echo "macOS環境を想定しています。ネイティブビルドを実行します..."
          if ! command -v cmake &> /dev/null; then
            echo "エラー: cmakeがインストールされていません"
            echo "Homebrewでインストールしてください: brew install cmake"
            exit 1
          fi
          cd crunch && \
          cmake -S. -Bbuild && \
          cmake --build build --parallel $(sysctl -n hw.ncpu) && \
          cp build/crunch ../server/resources/bin/crunch
        else
          echo "Linux環境を想定しています。Dockerでビルドを実行します..."
          docker run --rm -v "${PWD}:/workspace" -w /workspace/crunch -e JOBS=$(nproc) ubuntu:latest bash -c "apt-get update && apt-get install -y cmake build-essential && cmake -S. -Bbuild && cmake --build build --parallel $JOBS && cp build/crunch /workspace/server/resources/bin/crunch"
        fi

  test:
    desc: テストを実行
    cmds:
      - cargo test -p image-uploader-server

  dev:
    desc: ローカルでフォアグランドでサーバー起動
    cmds:
      - cargo run -p image-uploader-server

  mock-storage:
    desc: モックストレージサーバーを起動
    cmds:
      - cargo run -p mock-storage

  start:
    desc: コンテナを立てる
    cmds:
      - docker build -t image-uploader-api ./
      - docker run --rm -p 9090:9090 --name image-uploader-api image-uploader-api
  
  stop:
    desc: コンテナを停止
    cmds:
      - docker stop image-uploader-api