version: 3

tasks:
  gen:api:
    desc: openAPIからコードを生成
    cmds:
      - docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate -i /local/docs/api.yaml -g rust-axum -o /local/generated --additional-properties=packageName=generated

  gen:crunch:
    desc: crunchをビルド
    cmds:
      - docker run --rm -v "${PWD}:/workspace" -w /workspace/crunch -e JOBS=$(nproc) ubuntu:latest bash -c "apt-get update && apt-get install -y cmake build-essential && cmake -S. -Bbuild && cmake --build build --parallel $JOBS && cp build/crunch /workspace/server/resources/bin"

  test:
    desc: テストを実行
    cmds:
      - cargo test -p image-uploader-server

  dev:
    desc: ローカルでフォアグランドでサーバー起動
    cmds:
      - cargo run -p image-uploader-server

  start:
    desc: コンテナを立てる
    cmds:
      - docker build -t image-uploader-api ./
      - docker run --rm -p 9090:9090 --name image-uploader-api image-uploader-api
  
  stop:
    desc: コンテナを停止
    cmds:
      - docker stop image-uploader-api