version: 3

tasks:
  gen:api:
    desc: openAPIからコードを生成
    cmds:
      - docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate -i /local/docs/api.yaml -g rust-axum -o /local/generated --additional-properties=packageName=generated

  dev:
    desc: フォアグランドでサーバー起動
    cmds:
      - cargo run -p image-uploader-server

  compose-up:
    desc: コンテナをビルド＆起動
    cmds:
      - docker-compose -f ./docker-compose.yaml up --build
  
  copmose-down:
    desc: コンテナを破棄
    cmds:
      - docker-compose -f ./docker-compose.yaml down