version: 3

tasks:
  gen:api:
    desc: openAPIからコードを生成
    cmds:
      - docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate -i /local/docs/api.yaml -g rust-axum -o /local/generated --additional-properties=packageName=generated

  gen:crunch:
    desc: crunchをビルド
    cmds:
      - docker run --rm -v "${PWD}:/workspace" -w /workspace/crunch -e JOBS=$(nproc) ubuntu:latest bash -c "apt-get update && apt-get install -y cmake build-essential && cmake -S. -Bbuild && cmake --build build --parallel $JOBS && cp build/crunch /workspace/bin"

  dev:
    desc: ローカルでフォアグランドでサーバー起動
    cmds:
      - cargo run -p image-uploader-server

  compose-up:
    desc: コンテナをビルド＆起動
    cmds:
      - docker-compose -f ./docker-compose.yaml up --build
  
  compose-down:
    desc: コンテナを破棄
    cmds:
      - docker-compose -f ./docker-compose.yaml down